### ISSUE TITLE
Crash after a swing.

### ISSUE THREAD

**Issue by AfterRebelion** [SanAndreasP/BetterCombatRebirth#1]
Forge version: 1.12.2 - 14.23.4.2747
Mod version: 1.5.0
Description:
After attacking with the primary button, it crashed. It was on singleplayer. Was using an axe on the primary hand, and nothing on the secondary hand.

Crash-report: https://gist.github.com/AfterRebelion/bea2b800ea10fdcf9ed8d3979b4274ae

**Comment by SanAndreasP** [comment]
can you give me the latest.log? Seems like the access transformer didn't get loaded

**Comment by AfterRebelion** [comment]
Updated the gist with latest.log

**Comment by SanAndreasP** [comment]
ohh, I'm dumb... I forgot to tell Forge to use the Access Transformer <.<

**Comment by SanAndreasP** [comment]
I've pushed a new update, you can get it here once it's approved: https://minecraft.curseforge.com/projects/better-combat-rebirth/files/2598836

**PS: don't forget to delete your config file (bettercombat.cfg), as the old update had a mess up**

**Comment by AfterRebelion** [comment]
Works great now, thanks for the quick fix!
