### ISSUE TITLE
other ways to black and white list certain items.

### ISSUE THREAD

**Issue by Darkmega18** [SanAndreasP/BetterCombatRebirth#2]
is there a way that non modders can get the proper class type to put into the black list tab? Also, I was hoping you'd consider doing it by whitelist only. Since I'm finding I can still punch things with weird things, like sticks, teleport rods and staffs from magic mods and potions and stuff and it's really kinda annoying in that regard. 

I'd much rather be able to specify perhaps a blanket blacklist with whitelisted items or classes of items that would work in an offhand and have all others remain as vanilla. for example you've already whitelisted anything that works like an axe, sword, shovel, pick or hoe then other tools and weapon types that don't quite work I'll just add them as I realize and test in creative and such.

**Comment by SanAndreasP** [comment]
The config file lets you add custom whitelisted/blacklisted items and item classes.

I was thinking on removing the blacklist functionality anyway, as it is kinda redundant.

If you find something that should work but doesn't, you can tell me as well, so I can add the class to the whitelist by default in upcoming versions.

**Comment by Darkmega18** [comment]
for now, potions and literally anything that's not specifically a tool of sorts. cause I can't exactly go dual fists kungfu style, but I can use literally any item thats not a tool to get unarmed damage for the case of a mod like the monk which improved unarmed melee etc. :V
