### ISSUE TITLE
Offhand ignores certain on hit/immunity triggers

### ISSUE THREAD

**Issue by Darkmega18** [SanAndreasP/BetterCombatRebirth#5]
As far as i've noticed so far there are some issues with offhand ignoring certain defensive abilities or damage immunities of mobs. 

For example the tiny spirits/souls in random things, they're meant to be only killable through magical damage. But the offhand ignores this and lets me attack them anyway.
![image](https://user-images.githubusercontent.com/8104689/43830223-20f319fe-9b44-11e8-9b74-5732ebcc623c.png)

A second one I noticed was that sometimes robotic parts cybernetic enemies spawn with the evasion skill that makes them have around a 60% chance to make a poof of white particles and not take any damage. offhand still makes them make a poof of particles but they take damage anyway. :V 

Aether Legacy also has the slider boss which is immune to everything but pickaxes from vanilla and the mod itself. but my sword in the offhand can go straight through it and damage it allowing me to cheese the boss since he doesn't wake up until the first hit of damage is dealt using a pick... >_>'
![image](https://user-images.githubusercontent.com/8104689/43830033-c1b8e982-9b43-11e8-8cda-86050337b9a4.png)

**Comment by Darkmega18** [comment]
found another one. Aether legacy's Valkyrie queen has an interaction on rightclick, but also damage immunity until you trigger her fight by fighting other lesser valkyries first. 
![image](https://user-images.githubusercontent.com/8104689/43830470-a6a83462-9b44-11e8-80c0-e9266dfa7a1a.png)

instead you end up just being able to cheesy tap her all the way. I probably also don't need to get into the sun spirit boss who probably needs a special way to beat him too... (yeah, I just spawned him in and smacked him over and over right a rightclick while he told me I was stupid. :V)

**Comment by SanAndreasP** [comment]
Please try out the new version: https://minecraft.curseforge.com/projects/better-combat-rebirth/files/2600094
